spring.application.name=zest-product-api

spring.datasource.url=jdbc:mysql://mysql:3306/zestdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret==ZestAssignmentSecretKeyFor1234567899876543211234567890987654321123456abc
#JwtMustBeAtLeastThirtyTwoCharactersLong
jwt.expiration=3600000